### ISSUE TITLE
Please connect this device with the Spotify App on your phone to Login or enter your credentials in the Settings dialog"

### ISSUE THREAD

**Issue by bdgra** [ldsz/plugin.audio.spotify#23]
Hello,

I recently installed a new device with Kodi 19 I tried to install the Spotify addon but unfortunately that doesn't work. I tried the version that was created by Marcel on Kodi 18 and that one works fine. Is there a solution for this?

**Comment by bdgra** [comment]
Don't know how but out of nowhere it works.

**Comment by satellitecam** [comment]
For anyone wondering in future, you need both Spotify Premium (free trial is ok) and [this tweak](https://forum.kodi.tv/showthread.php?tid=265356&pid=3083161#pid3083161).
